apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operators.coreos.com/v1alpha1","kind":"Subscription","metadata":{"annotations":{},"name":"openshift-pipelines-operator","namespace":"openshift-operators"},"spec":{"channel":"latest","name":"openshift-pipelines-operator-rh","source":"do288-catalog-cs","sourceNamespace":"openshift-marketplace"}}
  creationTimestamp: "2024-06-19T12:07:05Z"
  generation: 1
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
  name: openshift-pipelines-operator
  namespace: openshift-operators
  resourceVersion: "2411660"
  uid: 1427aff4-2115-4038-a675-20ab19aa7421
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  source: do288-catalog-cs
  sourceNamespace: openshift-marketplace
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: do288-catalog-cs
      namespace: openshift-marketplace
      resourceVersion: "75235"
      uid: 70e0017e-1cb9-4481-b8af-b8ad1c8809de
    healthy: true
    lastUpdated: "2024-06-19T12:07:05Z"
  conditions:
  - lastTransitionTime: "2024-06-19T12:07:05Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  - status: "False"
    type: BundleUnpacking
  - message: 'failed to populate resolver cache from source do288-catalog-cs/openshift-marketplace:
      failed to list bundles: rpc error: code = Unavailable desc = connection error:
      desc = "transport: Error while dialing dial tcp: lookup do288-catalog-cs.openshift-marketplace.svc
      on 172.30.0.10:53: read udp 10.8.0.18:32888->172.30.0.10:53: read: connection
      refused"'
    reason: ErrorPreventedResolution
    status: "True"
    type: ResolutionFailed
  currentCSV: openshift-pipelines-operator-rh.v1.14.3
  installPlanGeneration: 1
  installPlanRef:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-4qwnt
    namespace: openshift-operators
    resourceVersion: "79765"
    uid: 9ba21a63-9b91-43c0-9e25-8475cb92e508
  installedCSV: openshift-pipelines-operator-rh.v1.14.3
  installplan:
    apiVersion: operators.coreos.com/v1alpha1
    kind: InstallPlan
    name: install-4qwnt
    uuid: 9ba21a63-9b91-43c0-9e25-8475cb92e508
  lastUpdated: "2025-03-19T02:24:40Z"
  state: AtLatestKnown
