apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scanner
spec:
  params:
  - name: SONAR_HOST_URL
    type: string
  - name: PROJECT_KEY
    type: string
  - name: PROJECT_DIR
    type: string
    default: .
  workspaces:
  - name: source
  steps:
  - name: run-sonarqube
    image: sonarsource/sonar-scanner-cli:latest
    workingDir: $(workspaces.source.path)/$(params.PROJECT_DIR)
    env:
    - name: SONAR_TOKEN
      valueFrom:
        secretKeyRef:
          name: sonarqube-token
          key: SONAR_TOKEN
    script: |
      #!/bin/sh
      sonar-scanner \
        -Dsonar.projectKey=$(params.PROJECT_KEY) \
        -Dsonar.sources=. \
        -Dsonar.host.url=$(params.SONAR_HOST_URL) \
        -Dsonar.login=$SONAR_TOKEN
