apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-commit-report
  serviceAccountName: github-sa
spec:
  params:
  - name: GIT_REPO_URL
    type: string
    default: "https://github.com/ravindra-be2004/pipeline"
  - name: GIT_USERNAME
    type: string
    default: "ravindra-be2004"
  - name: GIT_EMAIL
    type: string
    default: "ravindra.be2004@gmail.com"
  - name: COMMIT_MSG
    type: string
    default: "Add Trivy scan report"
  - name: REPORT_FILE
    type: string
    default: "trivy-report.txt"
  - name: REPORT_DIR
    type: string
    default: "reports"
  workspaces:
  - name: source
    description: Workspace containing the scan report
  steps:
    #    git config --global user.email "ravindra.be2004@gmail.com"
    #    git config --global user.name "ravindra-be2004"

    - name: commit-push
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        #   git config --global --add safe.directory /workspace/source
        git config --global user.email "ravindra.be2004@gmail.com"
        git config --global user.name "ravindra-be2004"
        echo "commit-push step started"
        git add .
        git commit -m "$(params.COMMIT_MSG)"
        git push origin HEAD

        echo "commit-push step finished"
