apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-deploy
spec:
  params:
    - name: image-name
      type: string
  workspaces:
  - name: source
  steps:
    - name: deploy
      image: registry.connect.redhat.com/seldonio/kubectl:1.14.3
      workingDir: $(workspaces.source.path)
      script: |
        kubectl create deployment myapp --image=$(params.image-name)  
        #        kubectl create deployment myapp --image=quay.io/ravindra_be2004/web11:latest  
